main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^blog/(?P<alias>[0-9A-Za-z\-]+)/$', views.blog_item, name='blog-item'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^faq/$', views.faq, name='contacts'),
    url(r'^environment/$', views.environment, name='environment'),
    #url(r'^services/$', views.services, name='services'),
    url(r'^testimonials/$', views.testimonials, name='testimonials'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^services/(?P<alias>[0-9A-Za-z\-]+)/$', views.service_item, name='service'),
    url(r'^services/(?P<service_lvl1>[0-9A-Za-z\-]+)/(?P<alias>[0-9A-Za-z\-]+)/$', views.service_item_lvl2, name='service_lvl2'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^portfolio/(?P<alias>[0-9A-Za-z\-]+)/$', views.portfolio_service, name='portfolio_service'),
    url(r'^portfolio/(?P<service>[0-9A-Za-z\-]+)/(?P<alias>[0-9A-Za-z\-]+)/$',
        views.portfolio_service_item, name='portfolio_service_item'),
    url(r'^(?P<alias>[0-9A-Za-z\-]+)/$', views.textpage, name='textpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    class Meta:
        abstract = True

    alias = models.SlugField(max_length=200, verbose_name=u"URL")
    seo_h1 = models.CharField(max_length=200, verbose_name="H1", null=True, blank=True)
    seo_title = models.CharField(max_length=200, verbose_name="Title", null=True, blank=True)
    seo_description = models.CharField(max_length=500, verbose_name="Description", null=True, blank=True)
    seo_keywords = models.CharField(max_length=500, verbose_name="Keywords", null=True, blank=True)
    menutitle = models.CharField(max_length=200, verbose_name=u"menutitle", null=True, blank=True)
    content = RichTextField(config_name='default', null=True, blank=True)


class TextPage(Page):
    class Meta:
        verbose_name = 'Text page'
        verbose_name_plural = 'Text pages'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160, unique=True)
    ordering = models.IntegerField('Ordering', default=0)
    main_menu = models.BooleanField('To main menu', default=False)

    def __str__(self):
        return self.name


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=40)
    ordering = models.IntegerField('Ordering', default=0)

    def __str__(self):
        return self.name


class BlogItem(Page):
    class Meta:
        verbose_name = 'Blog item'
        verbose_name_plural = 'Blog items'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    image_preview = models.FileField('Image Preview')
    datetime = models.DateTimeField('Add date', auto_now_add=True)
    ordering = models.IntegerField('Ordering', default=0)
    tags = models.ManyToManyField(Tag, verbose_name='Tags', blank=True)
    second_title = models.CharField('Second Title', max_length=160, null=True, blank=True)
    blockquote = models.TextField('Block quote', null=True, blank=True)
    image_under_blockquote = models.ImageField('Image under blockquote', null=True, blank=True, help_text='fill in together "Text under Block quote"')
    text_under_blockquote = models.TextField('Text under Block quote', null=True, blank=True, help_text='fill in together "Image under blockquote"')
    desc_before_video = RichTextField(config_name='default', null=True, blank=True, verbose_name='text before video')
    video = models.CharField('Video', max_length=160, help_text='https://www.youtube.com/embed/Z22t2gzs5Ds', null=True, blank=True)

    def __str__(self):
        return self.name


class OurProject(Page):
    class Meta:
        verbose_name = 'Our Project'
        verbose_name_plural = 'Our Projects'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    image_preview = models.FileField('Image Preview')
    datetime = models.DateTimeField('Add Date', auto_now_add=True)
    ordering = models.IntegerField('Ordering', default=0)


    def __str__(self):
        return self.name


class Service(Page):
    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    image_preview = models.FileField('Image Preview', null=True, blank=True)
    image_for_slider = models.FileField('Image for slider', null=True, blank=True, help_text='wide image')
    ordering = models.IntegerField('Ordering', default=0)

    def __str__(self):
        return self.name


class ServiceItem(Page):
    class Meta:
        verbose_name = 'Service item'
        verbose_name_plural = 'Service items'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    image_preview = models.FileField('Image Preview', null=True, blank=True)
    service = models.ForeignKey(Service, verbose_name='Main Service', related_name="sub_services", on_delete=models.SET_NULL, null=True,
                                help_text='Complete this field')
    ordering = models.IntegerField('Ordering', default=0)

    def __str__(self):
        return self.name


class PortfolioImage(models.Model):
    class Meta:
        verbose_name = 'Portfolio Image'
        verbose_name_plural = 'Portfolio Images'
        ordering = ['ordering']

    image_preview = models.FileField('Image')
    ordering = models.IntegerField('Ordering', default=0)
    portfolio = models.ForeignKey('Portfolio', models.CASCADE, verbose_name="Portfolio",
                                  related_name="portfolio_images", null=True, blank=True)

    def __str__(self):
        return str(self.pk)


class Portfolio(Page):
    class Meta:
        verbose_name = 'Portfolio'
        verbose_name_plural = 'Portfolio Item'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    image_preview = models.FileField('Image Preview', null=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='Tags', blank=True)
    datetime = models.DateTimeField(auto_now_add=True, verbose_name="Post Date", null=True, blank=True)
    service = models.ForeignKey(Service, models.CASCADE, verbose_name='Main Service')
    tags = models.ManyToManyField(ServiceItem, verbose_name='Services', related_name="all_services", blank=True)
    ordering = models.IntegerField('Ordering', default=0)

    def __str__(self):
        return self.name


class FAQ(models.Model):
    class Meta:
        verbose_name = 'FAQ item'
        verbose_name_plural = 'FAQ items'
        ordering = ['ordering']

    name = models.CharField('Name', max_length=160)
    text = models.TextField('Text', default='')
    ordering = models.IntegerField('Ordering', default=0)

    def __str__(self):
        return self.name


class Review(models.Model):
    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'
        ordering = ['-datetime']

    author = models.CharField('Sender', max_length=80)
    rating = models.IntegerField('Rating', default=5)
    active = models.BooleanField('Activity', default=False)
    text = models.TextField('Review')
    datetime = models.DateTimeField('Add Date')

    def __str__(self):
        return self.author

main/views.py
import requests
from django.template import loader
from django.http import HttpResponse, JsonResponse
from django.template.context_processors import csrf
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.conf import settings as django_settings
from django.core.mail import send_mail, BadHeaderError, EmailMessage, get_connection

from .models import *

# Create your views here.
def default_context(request, alias, object):
    c = {}
    c.update(csrf(request))

    data = get_object_or_404(object, alias=alias)

    main_menu = TextPage.objects.filter(main_menu=True)
    services = Service.objects.all()

    context_object = {
        'data': data,
        'c': c,
        'main_menu': main_menu,
        'services': services,
    }

    return context_object


def index(request):
    context_data = default_context(request, 'index', TextPage)

    template = loader.get_template('main.html')

    blog_items = BlogItem.objects.all()[:10]
    faqs = FAQ.objects.all()
    reviews = Review.objects.all()[:5]
    portfolio_items = Portfolio.objects.all()[:10]

    context_data.update({
        'faqs': faqs,
        'blog_items': blog_items,
        'reviews': reviews,
        'portfolio_items': portfolio_items
    })

    return HttpResponse(template.render(context_data))


def textpage(request, alias):
    context_data = default_context(request, alias, TextPage)

    template = loader.get_template('textpage.html')

    services = Service.objects.all()[:5]

    context_data.update({
        'services': services
    })

    return HttpResponse(template.render(context_data))


def blog(request):
    context_data = default_context(request, 'blog', TextPage)

    template = loader.get_template('blog.html')

    tags = Tag.objects.all()

    active_tags = []

    if request.GET.get('tag'):
        if request.META.get('HTTP_REFERER') == (
                ('https://' if request.is_secure() else 'http://') + request.get_host() + request.get_full_path()):
            blog_items = BlogItem.objects.all()[:10]
            return HttpResponseRedirect(reverse('main:blog', kwargs={}))
        active_tags = [int(request.GET.get('tag', 0))]
        blog_items = BlogItem.objects.filter(tags__pk__in=[request.GET.get('tag')])
    else:
        blog_items = BlogItem.objects.all()[:10]

    context_data.update({
        'blog_items': blog_items,
        'active_tags': active_tags,
        'tags': tags
    })

    return HttpResponse(template.render(context_data))

def blog_item(request, alias):
    context_data = default_context(request, alias, BlogItem)

    template = loader.get_template('article.html')

    context_data.update({

    })

    return HttpResponse(template.render(context_data))

def services(request):
    context_data = default_context(request, 'services', TextPage)

    template = loader.get_template('main_level.html')

    return HttpResponse(template.render(context_data))


def faq(request):
    context_data = default_context(request, 'faq', TextPage)

    template = loader.get_template('faq.html')

    context_data.update({
        'faq': FAQ.objects.all()
    })

    return HttpResponse(template.render(context_data))


def service_item(request, alias):
    context_data = default_context(request, alias, Service)

    template = loader.get_template('main_level.html')

    blog = BlogItem.objects.all()[:5]

    active_tags = []

    if request.GET.get('tag'):
        if request.META.get('HTTP_REFERER') == (
                ('https://' if request.is_secure() else 'http://') + request.get_host() + request.get_full_path()):
            portfolio_items = Portfolio.objects.all()[:10]
            return HttpResponseRedirect(reverse('main:service', kwargs={'alias': context_data['data'].alias}))
        active_tags = [int(request.GET.get('tag', 0))]
        portfolio_items = Portfolio.objects.filter(tags__pk__in=[request.GET.get('tag')], service=context_data['data'])
    else:
        portfolio_items = Portfolio.objects.filter(service=context_data['data'])[:10]


    context_data.update({
        'blog': blog,
        'portfolio_items': portfolio_items,
        'active_tags': active_tags,
    })

    return HttpResponse(template.render(context_data))


def service_item_lvl2(request, service_lvl1, alias):
    service = get_object_or_404(Service, alias=service_lvl1)

    context_data = default_context(request, alias, ServiceItem)

    template = loader.get_template('second_level.html')

    blog = BlogItem.objects.all()[:5]

    context_data.update({
        'portfolio_items': Portfolio.objects.filter(tags__pk__in=[context_data['data'].pk], service=service),
        'blog': blog,
    })

    return HttpResponse(template.render(context_data))


def about(request):
    context_data = default_context(request, 'about', TextPage)

    template = loader.get_template('about.html')

    portfolio_items = Portfolio.objects.all()[:7]

    reviews = Review.objects.all()[:5]

    context_data.update({
        'reviews': reviews,
        'portfolio_items': portfolio_items
    })

    return HttpResponse(template.render(context_data))

def testimonials(request):
    context_data = default_context(request, 'testimonials', TextPage)

    template = loader.get_template('testimonials.html')

    services = Service.objects.all()[:5]
    reviews = Review.objects.all()[:5]

    context_data.update({
        'reviews': reviews,
        'services': services

    })

    return HttpResponse(template.render(context_data))

def portfolio(request):
    context_data = default_context(request, 'portfolio', TextPage)

    template = loader.get_template('portfolio.html')

    portfolio_items = Portfolio.objects.all()[:10]

    context_data.update({
        'portfolio_items': portfolio_items
    })

    return HttpResponse(template.render(context_data))


def contacts(request):
    context_data = default_context(request, 'contacts', TextPage)

    template = loader.get_template('contacts.html')

    return HttpResponse(template.render(context_data))


def environment(request):
    context_data = default_context(request, 'environment', TextPage)

    template = loader.get_template('environment.html')

    return HttpResponse(template.render(context_data))


def portfolio_service(request, alias):
    context_data = default_context(request, alias, Service)

    template = loader.get_template('portfolio_second.html')

    tags = Tag.objects.all()

    active_tags = []

    if request.GET.get('tag'):
        if request.META.get('HTTP_REFERER') == (
                ('https://' if request.is_secure() else 'http://') + request.get_host() + request.get_full_path()):
            portfolio_items = Portfolio.objects.all()[:10]
            return HttpResponseRedirect(reverse('main:portfolio_service', kwargs={'alias': context_data['data'].alias}))
        active_tags = [int(request.GET.get('tag', 0))]
        portfolio_items = Portfolio.objects.filter(tags__pk__in=[request.GET.get('tag')], service=context_data['data'])
    else:
        portfolio_items = Portfolio.objects.filter(service=context_data['data'])[:10]

    context_data.update({
        'tags': tags,
        'active_tags': active_tags,
        'portfolio_items': portfolio_items
    })

    return HttpResponse(template.render(context_data))


def portfolio_service_item(request, service, alias):
    get_object_or_404(Service, alias=service)
    context_data = default_context(request, alias, Portfolio)

    template = loader.get_template('case_page.html')

    active_tags = []

    if request.GET.get('tag'):
        if request.META.get('HTTP_REFERER') == (
                ('https://' if request.is_secure() else 'http://') + request.get_host() + request.get_full_path()):
            portfolio_items = Portfolio.objects.filter(service=context_data['data'].service)[:10]
            return HttpResponseRedirect(reverse('main:portfolio_service_item', kwargs={'service': context_data['data'].service.alias, 'alias': context_data['data'].alias}))
        active_tags = [int(request.GET.get('tag', 0))]
        portfolio_items = Portfolio.objects.filter(service=context_data['data'].service, tags__pk__in=[request.GET.get('tag')])
    else:
        portfolio_items = Portfolio.objects.filter(service=context_data['data'].service)[:10]

    context_data.update({
        'active_tags': active_tags,
        'portfolio_items': portfolio_items,
        'blog': BlogItem.objects.all()[:10]
    })

    return HttpResponse(template.render(context_data))


def ajax(request):
    if request.is_ajax():
        if request.POST.get('type', None) == 'send_form':
            from email.mime.text import MIMEText
            from email.mime.multipart import MIMEMultipart
            _default = 'Не указано'
            connection = get_connection(
                host=django_settings.EMAIL_HOST,
                username=django_settings.EMAIL_HOST_USER,
                password=django_settings.EMAIL_HOST_PASSWORD
            )
            name = request.POST.get('name', _default)
            phone = request.POST.get('phone', _default)
            email = request.POST.get('email', _default)
            message = request.POST.get('message', _default)
            if not name or not phone:
                return HttpResponse('error')
            files = []
            messaga = u'Order info:<br>Name: {}<br>Phone: {}<br>E-mail: {}<br>Message: {}'.format(
                name, phone, email, message)
            recipients = [django_settings.EMAIL_HOST_USER_RECIP]
            tlg_message = messaga.replace('<br>', '\n')
            requests.get(f"https://api.telegram.org/bot{django_settings.TELEGRAM_BOT}/sendMessage?chat_id={django_settings.TELEGRAM_GROUP}&text={tlg_message}")
            subject = u'Order from site'
            mail = EmailMessage(subject, messaga, django_settings.EMAIL_HOST_USER, recipients,
                                connection=connection)

templates/about.html
{% extends '_base.html' %}

{% load static %}

{% block content %}
<section class="about_top">
    <div class="wrapper wrapper-about_top">
        <div class="about_top__left">
            <div class="about_top__our animation animation_left">Our philosophy</div>
            <div class="about_top__cur animation animation_left">“Our professionalism has nothing to do with getting paid for our services. We aim to perform at the highest level possible with integrity and honesty.”</div>
            <div class="about_date animation animation_left">
                <div class="about_date__top">Established in</div>
                <div class="about_date__date">2011</div>
            </div>
        </div>
        <div class="about_top__right animation animation_right">
            <h2 class="about_top__h2">About company</h2>
            <div class="about_top__text">REWTS Trees and Gardens specialise in all aspects of horticulture and arboriculture including tree surgery, garden landscaping and garden maintenance.</div>
            <div class="about_top__text">We are a well established Suffolk based company with our main base near Ipswich with the majority of our work being located in and around Bury St. Edmunds, Stowmarket and Ipswich.</div>
            <div class="about_top__text">Whether you need emergency tree help, your garden re-designed, or a regular maintenance service, REWTS are fully equipped to provide all of these.</div>
        </div>
    </div>
</section>
<section class="why">
    <div class="wrapper wrapper-why">
        <div class="why__wrp why__wrp-top">
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Free consultation</h3>
                <div class="main_utps__text">We are happy to visit and discuss your potential projects, offer plenty of ideas and inspiration.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Fair <br /> Price</h3>
                <div class="main_utps__text">Our prices reflect the projects and the skill involved.</div>
            </article>
            <h2 class="why__h2 animation animation_right">Why us?</h2>
        </div>
        <div class="why__wrp why__wrp-bottom">
            <article class="main_utps__utp main_utps__utp-mob animation animation_bot">
                <h3 class="main_utps__title">Free consultation</h3>
                <div class="main_utps__text">We are happy to visit and discuss your potential projects, offer plenty of ideas and inspiration.</div>
            </article>
            <article class="main_utps__utp main_utps__utp-mob animation animation_bot">
                <h3 class="main_utps__title">Fair <br /> Price</h3>
                <div class="main_utps__text">Our prices reflect the projects and the skill involved.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Our <br /> Reputation</h3>
                <div class="main_utps__text">Through the years we have established a solid reputation with customers returning to us time and again.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Recommendations</h3>
                <div class="main_utps__text">The majority of our work comes by word of mouth from satisfied customers passing on our name.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Environmental Promise</h3>
                <div class="main_utps__text">We take the environment extremly seriously and do everything possible to make a positive impact.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Reliability <br /> & Trust</h3>
                <div class="main_utps__text">We turn up! We always return your calls. We won’t leave you waiting.</div>
            </article>
            <article class="main_utps__utp animation animation_bot">
                <h3 class="main_utps__title">Complex projects</h3>
                <div class="main_utps__text">We love the challenge of working on complicated and technical designs.</div>
            </article>
        </div>
        <div class="button button-why animation animation_right open_enquery">Click to request design project</div>
    </div>
</section>
<section class="exp">
    <div class="wrapper wrapper-exp">
        <img class="exp__img-1 animation animation_left" src="{% static 'img/exp-1.jpg' %}" alt="">
        <img class="exp__img-2 animation animation_right" src="{% static 'img/exp-2.jpg' %}" alt="">
        <div class="exp__wrp">
            <h2 class="exp__h2 animation animation_bot">Experienced team using quality equipment </h2>
            <article class="exp__el animation animation_bot">
                <img class="exp__image" src="{% static 'img/exp__image-1.svg' %}" alt="">
                <div class="exp__right">
                    <h3 class="exp__h3">Our team</h3>
                    <div class="exp__text">All our employees are trained and have certificates confirming their qualifications.</div>
                </div>
            </article>
            <article class="exp__el animation animation_bot">
                <img class="exp__image" src="{% static 'img/exp__image-2.svg' %}" alt="">
                <div class="exp__right">
                    <h3 class="exp__h3">Our equipment</h3>
                    <div class="exp__text">We only use the most modern and efficient environmentally friendly equipment.</div>
                </div>
            </article>
        </div>
    </div>
</section>
<section class="our_ser">
    <div class="wrapper wrapper-our_ser">
        <h2 class="our_ser__h2  animation animation_left">Our services</h2>
        {% for s in services %}
            {% if forloop.counter < 4 %}
        <div class="our_ser__col animation animation_bot">
            <div class="footer__title">{{ s.name }}</div>
            <nav class="navs navs-our_ser">
                {% for i in s.sub_services.all %}
                <a href="{% url 'main:service_lvl2' s.alias i.alias %}" class="navs__nav">{{ i.name }}</a>
                {% endfor %}
            </nav>
        </div>
            {% endif %}
        {% endfor %}
        <div class="our_ser__col our_ser__col-last animation animation_right">
        {% for s in services %}
            {% if forloop.counter > 3 %}
            <a href="{% url 'main:service' s.alias %}" class="footer__title">{{ s.name }}</a>
            {% endif %}
        {% endfor %}
        </div>
    </div>
</section>
{% include 'inc/main_slider.html' %}
{% include 'inc/our_projects.html' %}
{% include 'inc/our_links.html' %}
{% include 'inc/our_customers.html' %}
{% endblock %}

templates/main.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<section class="main_banner">
    <div class="wrapper wrapper-main_banner">
        <div class="main_banner__h1 animation animation_bot">
            <a href="/services/tree-surgery/">Tree surgery</a>
            <a href="/services/garden-landscaping/">Landscaping</a>
            <a href="services/garden-maintenance/">Maintenance</a>
        </div>
        <div class="main_banner__right">
            <div class="main_banner__title animation animation_bot">REWTS</div>
            <div class="main_banner__text animation animation_bot">We are a well established Suffolk based company with our main base near Ipswich with the majority of our work being located in and around Bury St. Edmunds, Stowmarket and Ipswich.</div>
            {% include 'inc/socials.html' %}
        </div>
        <div class="button button-main_banner animation animation_left open_project">Click to request design project</div>
    </div>
</section>
{% include 'inc/main_slider.html' %}
<div class="main_utps">
    <div class="wrapper wrapper-main_utps animation animation_bot">
        <div class="main_utps__utp">
            <div class="main_utps__title">Free consultation</div>
            <div class="main_utps__text">We are happy to visit and discuss your potential projects, offer plenty of ideas and inspiration.</div>
        </div>
        <div class="main_utps__utp">
            <div class="main_utps__title">Fair <br /> Price</div>
            <div class="main_utps__text">Our prices reflect the projects and the skill involved.</div>
        </div>
        <div class="main_utps__utp">
            <div class="main_utps__title">Environmental Promise</div>
            <div class="main_utps__text">We take the environment extremly seriously and do everything possible to make a positive impact.</div>
        </div>
        <div class="main_utps__utp">
            <div class="main_utps__title">Reliability <br /> & Trust</div>
            <div class="main_utps__text">We turn up! We always return your calls. We won’t leave you waiting.</div>
        </div>
        <div class="main_utps__utp">
            <div class="main_utps__title">Complex projects</div>
            <div class="main_utps__text">We love the challenge of working on complicated and technical designs.</div>
        </div>
    </div>
</div>
{% include 'inc/our_projects.html' %}
{% include 'inc/what.html' %}
<section class="team">
    <div class="wrapper wrapper-team">
        <div class="team__wrp animation animation_left">
            <h2 class="team__h2">Our team</h2>
            <div class="team__right">
                <div class="team__text">Between us we have a mix of skills and qualifications which allows us to undertake a wide range of projects. <br />We take pride in our work. It’s personal to us, ensuring we work to the highest standard.</div>
                <a href="{% url 'main:about' %}" class="our__link our__link-team">
                <span>More about REWTS</span>
                </a>
            </div>
        </div>
        <img class="team__image animation animation_right" src="{% static 'img/team__image.png' %}" alt="">
    </div>
</section>
{% include 'inc/create_project.html' %}
<section class="env">
    <div class="wrapper wrapper-env">
        <div class="env__wrp">
            <h2 class="env__h2 animation animation_left">Environmental promise</h2>
            <div class="env__block env__block-env animation animation_left">
                <img class="create__img" src="{% static 'img/env__img.svg' %}" alt="">
                <div class="create__text creat__text-env">REWTS have a strong environmentally friendly work ethic and strive to maximise the positive impact we have on the environment.</div>
            </div>
            <a href="/environment/" class="our__link animation animation_left">
            <span>Find out More</span>
            </a>
        </div>
        <img class="env__image animation animation_right" src="{% static 'img/env__image.png' %}" alt="">
    </div>
</section>
{% include 'inc/our_links.html' %}
{% include 'inc/our_customers.html' %}
<section class="faq">
    <div class="wrapper wrapper-faq">
        <h2 class="what__h2 what__h2-faq animation animation_bot">FAQ</h2>
        <div class="faq__wrp">
            {% for f in faqs %}
            {% if forloop.counter < 4 %}
            <div class="faq__el animation animation_bot">
                <div class="faq__title">{{ f.name }}</div>
                <div class="faq__content">{{ f.text|safe }}</div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div style="width: 70%;">
            <a href="/faq/" class="our__link animation animation_bot"><span>More</span></a>
            <a href="javascript:" class="our__link animation animation_bot" style="float: right;">
                <span class="open_enquery">Ask your question</span>
            </a>
        </div>
    </div>
</section>
<section class="latest">
    <div class="wrapper wrapper-latest">
        <div class="latest__left">
            <div class="latest__wp">
                <h2 class="latest__h2 animation animation_left">Latest from the blog</h2>
                <div class="latest_slider__left animation animation_left">
                    {% for i in blog_items %}
                    <a href="{% url 'main:blog-item' i.alias %}" class="latest_slider__slide">
                        <div class="latest_slider__image" style="background-image: url({% if i.image_preview %}{{ i.image_preview.url }}{% endif %});"></div>
                        <div class="latest_slider__date">{{ i.datetime }}</div>
                        <div class="latest_slider__title">{{ i.name }}</div>
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="latest__nav animation animation_left">
            </div>
        </div>
        <div class="latest__right">
            <div class="latest_slider animation animation_right">
                {% for i in blog_items %}
                {% if forloop.counter > 2 %}
                <a href="{% url 'main:blog-item' i.alias %}" class="latest_slider__slide">
                    <div class="latest_slider__image" style="background-image: url({% if i.image_preview %}{{ i.image_preview.url }}{% endif %});"></div>
                    <div class="latest_slider__date">{{ i.datetime }}</div>
                    <div class="latest_slider__title">{{ i.name }}</div>
                </a>
                {% endif %}
                {% endfor %}
            </div>
            <a href="{% url 'main:blog' %}" class="our__link animation animation_right">
            <span>Read all</span>
            </a>
        </div>
    </div>
</section>
{% endblock %}