main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^blog/(?P<alias>[0-9A-Za-z\-]+)/$', views.blog_item, name='blog-item'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^faq/$', views.faq, name='contacts'),
    url(r'^environment/$', views.environment, name='environment'),
    #url(r'^services/$', views.services, name='services'),
    url(r'^testimonials/$', views.testimonials, name='testimonials'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^services/(?P<alias>[0-9A-Za-z\-]+)/$', views.service_item, name='service'),
    url(r'^services/(?P<service_lvl1>[0-9A-Za-z\-]+)/(?P<alias>[0-9A-Za-z\-]+)/$', views.service_item_lvl2, name='service_lvl2'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^portfolio/(?P<alias>[0-9A-Za-z\-]+)/$', views.portfolio_service, name='portfolio_service'),
    url(r'^portfolio/(?P<service>[0-9A-Za-z\-]+)/(?P<alias>[0-9A-Za-z\-]+)/$',
        views.portfolio_service_item, name='portfolio_service_item'),
    url(r'^(?P<alias>[0-9A-Za-z\-]+)/$', views.textpage, name='textpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/case_page_menu.html
{% load static %}
<div class="page_menu animation animation_right">
    <div class="page_menu__block">
        <div class="page_menu__title">We also do</div>
        <div class="page_menu__texts">
            {% for s in services %}
                {% if data.alias != s.alias %}
                <a href="{% url 'main:service' s.alias %}" class="page_menu__text">{{ s.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
        <a href="javascript:" class="what__link open_enquery" style="margin-top: 40px;">Free Consultation</a>
    </div>
    <div class="page_menu__article">
        <div class="page_menu__title">Articles on the subject</div>
        <section class="main_slider main_slider-page">
            <div class="main_slider__button">
                <span>Next</span>
            </div>
            <div class="main_slider__wrp">
                {% for b in blog %}
                <div class="main_slider__slide {% if forloop.first %}active{% endif %}">
                    <div class="main_slider__wp">
                        <div class="main_slider__back paral" style="background-image: url({{ b.image_preview.url }});"></div>
                    </div>
                    <div class="page_slider__bot">
                        <div class="page_slider__data">
                            {{ b.datetime|date:"d S M" }} {{ b.datetime|date:"Y" }}
                        </div>
                        <div class="page_slider__desc">{{ b.name }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        <a href="{% url 'main:blog' %}" class="our__link">
        <span>Read all</span>
        </a>
    </div>
</div>

templates/inc/create_project.html
{% load static %}
<section class="create">
  <div class="wrapper wrapper-creat">
    <div class="create__left animation animation_left">
      <div class="create__image"></div>
      <div class="create__bottom">
        <a href="javascript:" class="what__link open_enquery">Request design project</a>
        <div class="create__or">or</div>
        <a href="javascript:" class="what__link open_project">Send us your drawings</a>
      </div>
    </div>
    <div class="create__right animation animation_right">
      <h2 class="create__h2">Create your project</h2>
      <div class="create__block">
        <img class="create__img" src="{% static 'img/creat__img.svg' %}" alt="">
        <div class="create__text">We offer the flexibility for you to create your own design or sketch. We are also happy to take on work from other designers or provide you with a design.</div>
      </div>
    </div>
  </div>
</section>

templates/inc/customers__slide.html
<div class="customers__el animation animation_bot">
    <div class="customers__wp">
        <div class="customers__lft">
            <div class="customers__name">{{ r.author }}</div>
            <div class="rating">
                <div class="rating__star {% if r.rating > 0 %}active{% endif %}"></div>
                <div class="rating__star {% if r.rating > 1 %}active{% endif %}"></div>
                <div class="rating__star {% if r.rating > 2 %}active{% endif %}"></div>
                <div class="rating__star {% if r.rating > 3 %}active{% endif %}"></div>
                <div class="rating__star {% if r.rating > 4 %}active{% endif %}"></div>
            </div>
        </div>
        <div class="customers__date">{{ r.datetime }}</div>
    </div>
    <div class="customers__text">{{ r.text|safe }}</div>
</div>

templates/inc/el.html
{% load static %}
<a href="{% url 'main:portfolio_service_item' p.service.alias p.alias  %}" class="our_main__slide our_main__slide-page our_main__slide-portfolio animation animation_bot">
  <div class="our_main__wrp">
    <div class="our_main__image" style="background-image: url({% if p.image_preview %}{{ p.image_preview.url }}{% endif %});">
      <div class="our_main__hover"></div>
    </div>
  </div>
  <div class="our_main__bottom">
    <div class="our_main__title">{{ p.name }}</div>
    <div class="our_main__text">{{ p.service.name }}</div>
    <div class="our_main__date">
      {{ p.datetime|date:"d S M" }} <br />
      {{ p.datetime|date:"Y" }}
    </div>
  </div>
</a>

templates/inc/main_slider.html
{% load static %}
<section class="main_slider animation animation_left">
    <div class="main_slider__button">
        <span>Next</span>
    </div>
    <div class="main_slider__wrp">
        {% for s in services %}
            <a href="{% url 'main:portfolio_service' s.alias %}" class="main_slider__slide {% if forloop.first %}active{% endif %}">
                <div class="main_slider__back paral" style="background-image: url({% if s.image_for_slider %}{{ s.image_for_slider.url }}{% endif %});"></div>
                <div class="main_slider__text">{{ s.name }}</div>
            </a>
        {% endfor %}
    </div>
</section>

templates/inc/our_customers.html
{% load static %}
<section class="customers">
    <div class="wrapper wrapper-customers">
        <img class="customers__image animation animation_left" src="{% static 'img/customers__image.png' %}" alt="">
        <div class="customers__wrp animation animation_right">
            <div class="customers__slider">
                {% for r in reviews %}
                <article class="customers__slide">
                    <h3 class="customers__h3">Our customers say</h3>
                    {% include 'inc/customers__slide.html' %}
                </article>
                {% endfor %}
            </div>
            <div class="customers__bot">
                <div class="customers__navs"></div>
                <a href="{% url 'main:testimonials' %}" class="our__link our__link-customers">
                <span>Read all</span>
                </a>
            </div>
        </div>
    </div>
</section>

templates/inc/our_links.html
{% load static %}
<section class="links">
  <div class="wrapper wrapper-links">
    <h2 class="what__h2 what__h2-links animation animation_bot">Our links</h2>
    <div class="links__slider animation animation_bot">
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-1.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-2.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-3.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-4.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-5.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-1.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-2.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-3.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-4.svg' %}" alt="">
      </div>
      <div class="links__slide">
        <img class="links__img" src="{% static 'img/links__img-5.svg' %}" alt="">
      </div>
    </div>
    <div class="links__navs animation animation_bot"></div>
  </div>
</section>

templates/inc/our_projects.html
{% load static %}
<section class="our">
    <div class="wrapper wrapper-our">
        <div class="our__wrp">
            <div class="our_main animation animation_left">
                {% for p in portfolio_items %}
                <div class="our_main__slide">
                    <div class="our_main__wrp">
                        <div class="our_main__image" style="background-image: url({{ p.image_preview.url }});">
                            <div class="our_main__hover"></div>
                        </div>
                    </div>
                    <div class="our_main__bottom">
                        <div class="our_main__title">{{ p.name }}</div>
                        <div class="our_main__text">{{ p.service.name }}</div>
                        <div class="our_main__date">
                          {{ p.datetime|date:"d S M" }} <br />
                          {{ p.datetime|date:"Y" }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <h2 class="our__h2 animation animation_bot">Our projects</h2>
            <div class="our__bot">
                <div class="our__navs"></div>
                <div class="our_second__wrp animation animation_right">
                    <div class="our_second">
                        {% for p in portfolio_items %}
                            <div class="our_second__slide" style="background-image: url({{ p.image_preview.url }});"></div>
                        {% endfor %}
                    </div>
                </div>
                <a href="/portfolio/" class="our__link">
                <span>More</span>
                </a>
            </div>
        </div>
    </div>
</section>

templates/inc/page_menu.html
{% load static %}
<div class="page_menu animation animation_right">
    {% if data.sub_services.all|length or data.service.sub_services.all|length %}
    <div class="page_menu__block">
        <div class="page_menu__title">Services</div>
        <div class="page_menu__texts">
            {% if data.service %}
            {% for i in data.service.sub_services.all %}
                <a href="{% url 'main:service_lvl2' data.service.alias i.alias %}" class="page_menu__text">{{ i.name }}</a>
            {% endfor %}
            {% else %}
            {% for i in data.sub_services.all %}
                <a href="{% url 'main:service_lvl2' data.alias i.alias %}" class="page_menu__text">{{ i.name }}</a>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div class="page_menu__block">
        <div class="page_menu__title">We also do</div>
        <div class="page_menu__texts">
            {% for s in services %}
                {% if data.alias != s.alias %}
                <a href="{% url 'main:service' s.alias %}" class="page_menu__text">{{ s.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="page_menu__article">
        <div class="page_menu__title">Articles on the subject</div>
        <section class="main_slider main_slider-page">
            <div class="main_slider__button">
                <span>Next</span>
            </div>
            <div class="main_slider__wrp">
                {% for b in blog %}
                <div class="main_slider__slide {% if forloop.first %}active{% endif %}">
                    <div class="main_slider__wp">
                        <div class="main_slider__back paral" style="background-image: url({{ b.image_preview.url }});"></div>
                    </div>
                    <div class="page_slider__bot">
                        <div class="page_slider__data">
                            {{ b.datetime|date:"d S M" }} {{ b.datetime|date:"Y" }}
                        </div>
                        <div class="page_slider__desc">{{ b.name }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        <a href="{% url 'main:blog' %}" class="our__link">
        <span>Read all</span>
        </a>
    </div>
</div>

templates/inc/what.html
{% load static %}
<section class="what">
    <div class="wrapper">
        <h2 class="what__h2 animation animation_bot">What we do</h2>
        <div class="what__wrapper">
            {% for s in services %}
            {% if forloop.counter == 1 %}
            <a href="{% url 'main:service' s.alias %}" class="elem animation animation_bot">
            {% elif forloop.counter == 2 %}
            <a href="{% url 'main:service' s.alias %}" class="elem elem-large animation animation_bot">
            {% elif forloop.counter == 3 %}
            <a href="{% url 'main:service' s.alias %}" class="elem elem-medium animation animation_bot">
            {% elif forloop.counter == 4 %}
            <a href="{% url 'main:service' s.alias %}" class="elem elem-small animation animation_bot">
            {% else %}
            <a href="{% url 'main:service' s.alias %}" class="elem elem-tiny animation animation_bot">
            {% endif %}
                <div class="elem__top" style="background-image: url({% if s.image_preview %}{{ s.image_preview.url }}{% endif %});">
                    <div class="elem__hover"><span>Discover</span></div>
                    <div class="elem__counter">0{{ forloop.counter }}.</div>
                </div>
                <div class="elem__title">{{ s.name }}</div>
            </a>
            {% endfor %}
        </div>
        <a href="javascript:" class="what__link open_enquery">Request Free Consultation</a>
    </div>
</section>